---
title: Patrick Reagan Running
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
description: Test site for Patrick
baseurl: ''
email: patrickreaganrunning@gmail.com
instagram_username: patrickreaganrunning
twitter_username: preaganrunning
instagram_URL: https://instagram.com/patrickreaganrunning
twitter_URL: https://twitter.com/preaganrunning
facebook_URL: https://www.facebook.com/patrickreaganrunning
strava_URL: https://www.strava.com/pros/10014836
